sudo: required

language: ruby

services:
  - docker

script: |
  docker build -t synker/synker-media-server:latest -t synker/synker-media-server:0.0.$TRAVIS_BUILD_NUMBER -f dockerfile . && \
  docker login -u=$DOCKER_USER -p=$DOCKER_PASS && \
  docker push "synker/synker-media-server"
  chmod +x ./trigger-buid.sh
  ./trigger-build.sh "Fazzani/synker-docker"
branches:
  only:
    - /^\d+\.\d+\.\d+$/
    - master
notifications: # set notification options
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change